#!/usr/bin/env python3
import os
import sys

#ugh... python
# as a temporary waystation while I think about proper internal file path 
# searching / resolution, I'll just have a script generate a header file
# with an array and a log(n) search mechanism... it's currently something
# like ~500 files, so this should be fine for now

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <source_dir> <output_header>")
        sys.exit(1)

    source_dir = os.path.abspath(sys.argv[1])
    output_header = os.path.abspath(sys.argv[2])

    scan_dirs = ["assets", "test"]
    entries = []

    excluded_extensions = ('.txt', '.cmake', '.fot', '.in', '.log', '.json')

    for sub in scan_dirs:
        full_sub = os.path.join(source_dir, sub)
        if not os.path.isdir(full_sub):
            continue
        for root, dirs, files in os.walk(full_sub):
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            for f in files:
                if f.startswith('.'):
                    continue
                if f.endswith(excluded_extensions):
                    continue
                full_path = os.path.join(root, f)
                rel_path = os.path.relpath(full_path, source_dir).replace('\\', '/')
                entries.append((f, rel_path))

    entries.sort(key=lambda x: (x[0], x[1]))

    os.makedirs(os.path.dirname(output_header), exist_ok=True)

    header_content = """// This file is auto-generated by the build process. Do not edit by hand.

#pragma once

#include <string_view>
#include <array>
#include <algorithm>
#include <filesystem>

namespace AssetIndex {

struct Entry {
    std::string_view filename;
    std::string_view relative_path;
};

inline constexpr Entry ENTRIES[] = {
"""

    for fname, rel_path in entries:
        fname_esc = fname.replace('\\', '\\\\').replace('"', '\\"')
        rel_esc = rel_path.replace('\\', '\\\\').replace('"', '\\"')
        header_content += f'    {{"{fname_esc}", "{rel_esc}"}},\n'

    header_content += f"""}};

inline constexpr size_t COUNT = {len(entries)};

inline std::string_view find_relative_path(std::string_view target)
    {{
    if (target.empty())
        return {{}};

    size_t last_slash = target.find_last_of("/\\\\");
    std::string_view fname = (last_slash == std::string_view::npos) ? target : target.substr(last_slash + 1);

    auto comp = [](const Entry& e, std::string_view key) {{
        return e.filename < key;
    }};

    auto it = std::lower_bound(std::begin(ENTRIES), std::end(ENTRIES), fname, comp);
    if (it == std::end(ENTRIES) || it->filename != fname)
        return {{}};

    if (last_slash == std::string_view::npos)
        return it->relative_path;

    for (; it != std::end(ENTRIES) && it->filename == fname; ++it)
        {{
        if (it->relative_path.size() >= target.size())
            {{
            size_t offset = it->relative_path.size() - target.size();
            if (offset == 0 || it->relative_path[offset - 1] == '/')
                {{
                bool match = true;
                for (size_t k = 0; k < target.size(); ++k)
                    {{
                    char c1 = it->relative_path[offset + k];
                    char c2 = target[k];
                    if (c1 != c2 && !(c1 == '/' && c2 == '\\\\'))
                        {{
                        match = false;
                        break;
                        }}
                    }}
                if (match)
                    return it->relative_path;
                }}
            }}
        }}

    return {{}};
    }}

inline std::string_view find_relative_path(const std::filesystem::path& target)
    {{
    return find_relative_path(std::string_view(target.native()));
    }}

}} // namespace AssetIndex
"""

    if os.path.exists(output_header):
        with open(output_header, 'r', encoding='utf-8') as f:
            if f.read() == header_content:
                return

    with open(output_header, 'w', encoding='utf-8') as f:
        f.write(header_content)

if __name__ == "__main__":
    main()
